services:
  yyassistant-client:
    image: "zinohome/yyassistant-client-au:v0.0.1"
    container_name: yyassistant-client-au
    hostname: yyassistant-client-au
    restart: unless-stopped
    ports:
      - "8000:8000/tcp"
    volumes:
      - "/data/yyasistant-client-au/.env:/opt/yyasistant-client-au/.env"
    networks:
      - 1panel-network
  yyassistant-server:
    image: "zinohome/yyassistant-server:v0.0.1"
    container_name: yyassistant-server
    hostname: yyassistant-server
    restart: unless-stopped
    #ports:
    #  - "8880:8880/tcp"
    volumes:
      - "/data/yyasistant-server/configs:/opt/yyasistant-server/configs"
    networks:
      - 1panel-network
networks:
  1panel-network:
    external: true